ALTER TABLE pagereports ADD COLUMN meta_keywords TEXT DEFAULT NULL;
ALTER TABLE pagereports ADD COLUMN h1_count INT NOT NULL DEFAULT 0;
ALTER TABLE pagereports ADD COLUMN h2_count INT NOT NULL DEFAULT 0;
ALTER TABLE pagereports ADD COLUMN readability_score FLOAT NOT NULL DEFAULT 0;
ALTER TABLE pagereports ADD COLUMN sim_hash VARCHAR(256) DEFAULT NULL;
ALTER TABLE pagereports ADD COLUMN schema_types VARCHAR(2048) DEFAULT NULL;
ALTER TABLE pagereports ADD COLUMN has_open_graph TINYINT NOT NULL DEFAULT 0;
ALTER TABLE pagereports ADD COLUMN has_twitter_card TINYINT NOT NULL DEFAULT 0;
